# Generated by Django 5.2.6 on 2025-10-12 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_start', models.DateTimeField()),
                ('rental_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='users.user')),
                ('vehicle', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicles.vehicle')),
            ],
        ),
    ]
