# Generated by Django 5.2.7 on 2025-10-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicles.vehicle'),
        ),
    ]
