# Generated by Django 5.2.7 on 2025-11-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Active (Unpaid/Pending)'), ('confirmed', 'Confirmed (Paid)'), ('completed', 'Completed (Returned)'), ('cancelled', 'Cancelled')], default='active', max_length=50),
        ),
    ]
