# Generated by Django 5.2.7 on 2025-11-03 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_payment_intent_id_rental_total_cost_and_more'),
        # Explicit dependency on users.0002 ensures that the user model's
        # schema changes (e.g. altering the PK) are applied before creating
        # or altering tables that reference the user model. Using
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL) resolves
        # to the first migration of the user app, which allowed an ordering
        # where rentals ran before users.0002 and caused ALTER errors.
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('rental', models.ForeignKey(db_column='rental_id', on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='rentals.rental')),
                ('reporter', models.ForeignKey(blank=True, db_column='reporter_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reporters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
