# Generated by Django 5.2.7 on 2025-11-03 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_damagereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='review', serialize=False, to='rentals.rental')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
