# Generated by Django 5.2.7 on 2025-11-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_review'),
        ('vehicles', '0003_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='rental_instances', to='vehicles.vehicle'),
        ),
    ]
