# Generated by Django 5.2.6 on 2025-10-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('availability_status', models.BooleanField(default=True)),
                ('rental_rate_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
