# Generated by Django 5.2.7 on 2025-11-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
