# Generated by Django 5.2.7 on 2025-11-16 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_current_location_vehicle_current_mileage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this vehicle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
